import mostrarExer1 from "./scripts/exercicio-1.js";
import mostrarExer2 from "./scripts/exercicio-2.js";
import mostrarExer3 from "./scripts/exercicio-3.js";
import mostrarExer4 from "./scripts/exercicio-4.js";
import mostrarExer5 from "./scripts/exercicio-5.js";
import mostrarExer6 from "./scripts/exercicio-6.js";
import mostrarExer7 from "./scripts/exercicio-7.js";
import mostrarExer8 from "./scripts/exercicio-8.js";
import mostrarExer9 from "./scripts/exercicio-9.js";
import mostrarExer10 from "./scripts/exercicio-10.js";
import mostrarExer11 from "./scripts/exercicio-11.js";
import mostrarExer12 from "./scripts/exercicio-12.js";
import mostrarExer13 from "./scripts/exercicio-13.js";
import mostrarExerVariaveis from "./scripts/variaveis.js";

document.getElementById("btn-exer1").addEventListener("click", mostrarExer1);
document.getElementById("btn-exer2").addEventListener("click", mostrarExer2);
document.getElementById("btn-exer3").addEventListener("click", mostrarExer3);
document.getElementById("btn-exer4").addEventListener("click", mostrarExer4);
document.getElementById("btn-exer5").addEventListener("click", mostrarExer5);
document.getElementById("btn-exer6").addEventListener("click", mostrarExer6);
document.getElementById("btn-exer7").addEventListener("click", mostrarExer7);
document.getElementById("btn-exer8").addEventListener("click", mostrarExer8);
document.getElementById("btn-exer9").addEventListener("click", mostrarExer9);
document.getElementById("btn-exer10").addEventListener("click", mostrarExer10);
document.getElementById("btn-exer11").addEventListener("click", mostrarExer11);
document.getElementById("btn-exer12").addEventListener("click", mostrarExer12);
document.getElementById("btn-exer13").addEventListener("click", mostrarExer13);
document.getElementById("btn-variaveis").addEventListener("click", mostrarExerVariaveis);